project_id = "mxprusqbnjhbqstmrgkt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
site_url = "https://whats-up-birthdays-buddy.vercel.app"
additional_redirect_urls = ["https://localhost:3000", "https://whats-up-birthdays-buddy.vercel.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.send-whatsapp-message]
verify_jwt = false

[functions.process-birthday-reminders]
verify_jwt = false