// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxprusqbnjhbqstmrgkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14cHJ1c3FibmpoYnFzdG1yZ2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDQ2NzQsImV4cCI6MjA2ODYyMDY3NH0.M6peGfySv6jY_Beg9OZT0E3c9D-EkMsFAToirPDjthw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});